version: "3.8"
services:
  traefik:
    image: "traefik:v2.6"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt-prod.acme.email=${LETS_ENCRYPT_EMAIL}"
      - "--certificatesresolvers.letsencrypt-prod.acme.storage=/data/acme.json"
      - "--certificatesresolvers.letsencrypt-prod.acme.tlschallenge=true"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./data/ingress:/data"
  frontend:
    container_name: datacrossways_frontend
    build:
      context: ./frontend
      args:
        BASE_URL: ${BASE_URL}
    ports:
      - 3000:80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`${BASE_URL}`) && !PathPrefix(`/api`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt-prod"
      - "traefik.http.routers.frontend.tls.domains[0].main=${BASE_URL}"
    environment:
      - REACT_APP_BASE_API_URL=https://${BASE_URL}/api
  api:
    container_name: datacrossways_api
    build: ./api
    ports:
      - 5000:5000
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    volumes:
      - ./secrets:/app/secrets
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`${BASE_URL}`) && PathPrefix(`/api`)"
      - "traefik.http.services.api.loadbalancer.server.port=5000"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=letsencrypt-prod"
      - "traefik.http.routers.api.tls.domains[0].main=${BASE_URL}"
    environment:
      - PORT=5000
      - APP_MODULE=app:app