version: "3.8"
services:
  frontend:
    container_name: datacrossways_frontend
    build: ./frontend
    ports:
      - 3000:3000
  api:
    container_name: datacrossways_api
    build: ./api
    ports:
      - 5000:5000
    volumes:
      - ./api/secrets:/apilock/secrets